#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# displaying some info when recieving a signal
sudo touch /var/run/myscript.pid
echo $$ >> /var/run/myscript.pid

trap "exit_sigquit" 3
trap "exit_sigterm" 15
trap "echo Y U no love me?!" 2

exit_sigterm()
{
	echo "I hate the kill command"
	sudo rm /var/run/myscript.pid
	exit 1
}

exit_sigquit()
{
	sudo rm /var/run/myscript.pid
	exit 1
}


while :
do
	echo "To infinity and beyond"
	sleep 2
done
