#!/usr/bin/env bash
# To infinity and beyond indefinitely.
# I am invincible!!! when receiving a SIGTERM signal.
trap "echo I am invincible!!!" 15

while :
do
	echo "To infinity and beyond"
	sleep 2
done
