#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.
hour=0
i=1
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	while [ $i -le 59 ]
	do
		echo $i
		i=$(( i + 1 ))
	done
	i=0
	hour=$(( hour + 1 ))
done
